"""Artifacts API -- serve files generated by the agent for user download."""

from __future__ import annotations

import logging
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import FileResponse
from pydantic import BaseModel

from odigos.api.deps import get_db, require_auth
from odigos.storage import ARTIFACTS_DIR, resolve_artifact_path

logger = logging.getLogger(__name__)

router = APIRouter(
    prefix="/api/artifacts",
    dependencies=[Depends(require_auth)],
)


@router.get("")
async def list_artifacts(conversation_id: str | None = None, db=Depends(get_db)):
    """List artifacts, optionally filtered by conversation."""
    if conversation_id:
        rows = await db.fetch_all(
            "SELECT * FROM artifacts WHERE conversation_id = ? ORDER BY created_at DESC",
            (conversation_id,),
        )
    else:
        rows = await db.fetch_all(
            "SELECT * FROM artifacts ORDER BY created_at DESC LIMIT 50",
        )
    return {"artifacts": [dict(r) for r in rows]}


@router.get("/{artifact_id}")
async def get_artifact(artifact_id: str, db=Depends(get_db)):
    """Get artifact metadata."""
    row = await db.fetch_one("SELECT * FROM artifacts WHERE id = ?", (artifact_id,))
    if not row:
        raise HTTPException(status_code=404, detail="Artifact not found")
    return dict(row)


@router.get("/{artifact_id}/content")
async def get_artifact_content(artifact_id: str, db=Depends(get_db)):
    """Get raw text content of an artifact for preview rendering."""
    row = await db.fetch_one("SELECT * FROM artifacts WHERE id = ?", (artifact_id,))
    if not row:
        raise HTTPException(status_code=404, detail="Artifact not found")

    content_type = row["content_type"]

    # For images and other binary types, return metadata only (preview uses /download endpoint)
    text_types = {"text/", "application/json", "application/xml", "application/x-yaml"}
    if not any(content_type.startswith(t) for t in text_types):
        return {
            "content": "",
            "content_type": content_type,
            "filename": row["filename"],
            "file_size": row.get("file_size", 0),
        }

    file_path = resolve_artifact_path(artifact_id, row["filename"], row.get("file_path"))
    if not file_path:
        raise HTTPException(status_code=404, detail="Artifact file missing from disk")

    content = file_path.read_text(encoding="utf-8")
    return {
        "content": content,
        "content_type": content_type,
        "filename": row["filename"],
        "file_size": row.get("file_size", 0),
    }


class ArtifactUpdate(BaseModel):
    content: str


@router.put("/{artifact_id}/content")
async def update_artifact_content(
    artifact_id: str,
    update: ArtifactUpdate,
    db=Depends(get_db),
):
    """Update raw text content of an artifact."""
    row = await db.fetch_one("SELECT * FROM artifacts WHERE id = ?", (artifact_id,))
    if not row:
        raise HTTPException(status_code=404, detail="Artifact not found")

    file_path = ARTIFACTS_DIR / artifact_id / row["filename"]
    if not file_path.exists():
        raise HTTPException(status_code=404, detail="Artifact file missing from disk")

    # Update file on disk
    file_path.write_text(update.content, encoding="utf-8")

    # Update file size in DB
    new_size = file_path.stat().st_size
    await db.execute(
        "UPDATE artifacts SET file_size = ? WHERE id = ?",
        (new_size, artifact_id),
    )

    return {"status": "updated", "file_size": new_size}


@router.get("/{artifact_id}/download")
async def download_artifact(artifact_id: str, db=Depends(get_db)):
    """Download an artifact file."""
    row = await db.fetch_one(
        "SELECT * FROM artifacts WHERE id = ?", (artifact_id,),
    )
    if not row:
        raise HTTPException(status_code=404, detail="Not found")

    filename = row["filename"]
    file_path = resolve_artifact_path(artifact_id, filename, row.get("file_path"))
    if not file_path:
        raise HTTPException(status_code=404, detail="File missing")

    return FileResponse(
        path=str(file_path),
        filename=filename,
        media_type=row["content_type"],
    )


@router.get("/{artifact_id}/thumbnail")
async def get_thumbnail(artifact_id: str, size: int = 400, db=Depends(get_db)):
    """Get a resized thumbnail of an image artifact. Fast loading for galleries."""
    row = await db.fetch_one("SELECT * FROM artifacts WHERE id = ?", (artifact_id,))
    if not row:
        raise HTTPException(status_code=404, detail="Not found")
    if not (row["content_type"] or "").startswith("image/"):
        raise HTTPException(status_code=400, detail="Not an image")

    file_path = resolve_artifact_path(artifact_id, row["filename"], row.get("file_path"))
    if not file_path:
        raise HTTPException(status_code=404, detail="File missing")

    # Generate thumbnail on the fly (cached by browser via etag)
    import io
    from PIL import Image
    size = min(max(size, 50), 800)
    img = Image.open(str(file_path))
    img.thumbnail((size, size), Image.LANCZOS)
    buf = io.BytesIO()
    img.save(buf, format="WEBP", quality=80)
    buf.seek(0)

    from fastapi.responses import StreamingResponse
    return StreamingResponse(
        buf,
        media_type="image/webp",
        headers={"Cache-Control": "public, max-age=86400"},
    )


@router.delete("/{artifact_id}")
async def delete_artifact(artifact_id: str, db=Depends(get_db)):
    """Delete an artifact."""
    row = await db.fetch_one("SELECT * FROM artifacts WHERE id = ?", (artifact_id,))
    if not row:
        raise HTTPException(status_code=404, detail="Artifact not found")

    # Delete file from disk
    artifact_dir = ARTIFACTS_DIR / artifact_id
    if artifact_dir.exists():
        import shutil
        shutil.rmtree(artifact_dir)

    await db.execute("DELETE FROM artifacts WHERE id = ?", (artifact_id,))
    return {"deleted": True}
