"""Artifacts API -- serve files generated by the agent for user download."""

from __future__ import annotations

import logging
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import FileResponse
from pydantic import BaseModel

from odigos.api.deps import get_db, require_auth

logger = logging.getLogger(__name__)

router = APIRouter(
    prefix="/api/artifacts",
    dependencies=[Depends(require_auth)],
)

ARTIFACTS_DIR = Path("data/artifacts")


@router.get("")
async def list_artifacts(conversation_id: str | None = None, db=Depends(get_db)):
    """List artifacts, optionally filtered by conversation."""
    if conversation_id:
        rows = await db.fetch_all(
            "SELECT * FROM artifacts WHERE conversation_id = ? ORDER BY created_at DESC",
            (conversation_id,),
        )
    else:
        rows = await db.fetch_all(
            "SELECT * FROM artifacts ORDER BY created_at DESC LIMIT 50",
        )
    return {"artifacts": [dict(r) for r in rows]}


@router.get("/{artifact_id}")
async def get_artifact(artifact_id: str, db=Depends(get_db)):
    """Get artifact metadata."""
    row = await db.fetch_one("SELECT * FROM artifacts WHERE id = ?", (artifact_id,))
    if not row:
        raise HTTPException(status_code=404, detail="Artifact not found")
    return dict(row)


@router.get("/{artifact_id}/content")
async def get_artifact_content(artifact_id: str, db=Depends(get_db)):
    """Get raw text content of an artifact for preview rendering."""
    row = await db.fetch_one("SELECT * FROM artifacts WHERE id = ?", (artifact_id,))
    if not row:
        raise HTTPException(status_code=404, detail="Artifact not found")

    file_path = ARTIFACTS_DIR / artifact_id / row["filename"]
    if not file_path.exists():
        raise HTTPException(status_code=404, detail="Artifact file missing from disk")

    # Only serve text-based content for preview
    content_type = row["content_type"]
    text_types = {"text/", "application/json", "application/xml", "application/x-yaml"}
    if not any(content_type.startswith(t) for t in text_types):
        raise HTTPException(status_code=400, detail="Binary artifacts cannot be previewed as text")

    content = file_path.read_text(encoding="utf-8")
    return {"content": content, "content_type": content_type, "filename": row["filename"]}


class ArtifactUpdate(BaseModel):
    content: str


@router.put("/{artifact_id}/content")
async def update_artifact_content(
    artifact_id: str,
    update: ArtifactUpdate,
    db=Depends(get_db),
):
    """Update raw text content of an artifact."""
    row = await db.fetch_one("SELECT * FROM artifacts WHERE id = ?", (artifact_id,))
    if not row:
        raise HTTPException(status_code=404, detail="Artifact not found")

    file_path = ARTIFACTS_DIR / artifact_id / row["filename"]
    if not file_path.exists():
        raise HTTPException(status_code=404, detail="Artifact file missing from disk")

    # Update file on disk
    file_path.write_text(update.content, encoding="utf-8")

    # Update file size in DB
    new_size = file_path.stat().st_size
    await db.execute(
        "UPDATE artifacts SET file_size = ? WHERE id = ?",
        (new_size, artifact_id),
    )

    return {"status": "updated", "file_size": new_size}


@router.get("/{artifact_id}/download")
async def download_artifact(artifact_id: str, db=Depends(get_db)):
    """Download an artifact file."""
    row = await db.fetch_one("SELECT * FROM artifacts WHERE id = ?", (artifact_id,))
    if not row:
        raise HTTPException(status_code=404, detail="Artifact not found")

    file_path = ARTIFACTS_DIR / artifact_id / row["filename"]
    if not file_path.exists():
        raise HTTPException(status_code=404, detail="Artifact file missing from disk")

    return FileResponse(
        path=str(file_path),
        filename=row["filename"],
        media_type=row["content_type"],
    )


@router.delete("/{artifact_id}")
async def delete_artifact(artifact_id: str, db=Depends(get_db)):
    """Delete an artifact."""
    row = await db.fetch_one("SELECT * FROM artifacts WHERE id = ?", (artifact_id,))
    if not row:
        raise HTTPException(status_code=404, detail="Artifact not found")

    # Delete file from disk
    artifact_dir = ARTIFACTS_DIR / artifact_id
    if artifact_dir.exists():
        import shutil
        shutil.rmtree(artifact_dir)

    await db.execute("DELETE FROM artifacts WHERE id = ?", (artifact_id,))
    return {"deleted": True}
