"""Artifacts API -- serve files generated by the agent for user download."""

from __future__ import annotations

import logging
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import FileResponse

from odigos.api.deps import get_db, require_auth

logger = logging.getLogger(__name__)

router = APIRouter(
    prefix="/api/artifacts",
    dependencies=[Depends(require_auth)],
)

ARTIFACTS_DIR = Path("data/artifacts")


@router.get("")
async def list_artifacts(conversation_id: str | None = None, db=Depends(get_db)):
    """List artifacts, optionally filtered by conversation."""
    if conversation_id:
        rows = await db.fetch_all(
            "SELECT * FROM artifacts WHERE conversation_id = ? ORDER BY created_at DESC",
            (conversation_id,),
        )
    else:
        rows = await db.fetch_all(
            "SELECT * FROM artifacts ORDER BY created_at DESC LIMIT 50",
        )
    return {"artifacts": [dict(r) for r in rows]}


@router.get("/{artifact_id}")
async def get_artifact(artifact_id: str, db=Depends(get_db)):
    """Get artifact metadata."""
    row = await db.fetch_one("SELECT * FROM artifacts WHERE id = ?", (artifact_id,))
    if not row:
        raise HTTPException(status_code=404, detail="Artifact not found")
    return dict(row)


@router.get("/{artifact_id}/download")
async def download_artifact(artifact_id: str, db=Depends(get_db)):
    """Download an artifact file."""
    row = await db.fetch_one("SELECT * FROM artifacts WHERE id = ?", (artifact_id,))
    if not row:
        raise HTTPException(status_code=404, detail="Artifact not found")

    file_path = ARTIFACTS_DIR / artifact_id / row["filename"]
    if not file_path.exists():
        raise HTTPException(status_code=404, detail="Artifact file missing from disk")

    return FileResponse(
        path=str(file_path),
        filename=row["filename"],
        media_type=row["content_type"],
    )


@router.delete("/{artifact_id}")
async def delete_artifact(artifact_id: str, db=Depends(get_db)):
    """Delete an artifact."""
    row = await db.fetch_one("SELECT * FROM artifacts WHERE id = ?", (artifact_id,))
    if not row:
        raise HTTPException(status_code=404, detail="Artifact not found")

    # Delete file from disk
    artifact_dir = ARTIFACTS_DIR / artifact_id
    if artifact_dir.exists():
        import shutil
        shutil.rmtree(artifact_dir)

    await db.execute("DELETE FROM artifacts WHERE id = ?", (artifact_id,))
    return {"deleted": True}
