import { useEffect, useState } from 'react'
import { get, del } from '@/lib/api'
import { Artifact, ArtifactCard } from '@/components/ArtifactCard'
import { ScrollArea } from '@/components/ui/scroll-area'
import { Trash2 } from 'lucide-react'

import { toast } from 'sonner'
import { Skeleton } from '@/components/ui/skeleton'

export default function ArtifactsPage() {
  const [artifacts, setArtifacts] = useState<Artifact[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    loadArtifacts()
  }, [])

  function loadArtifacts() {
    setLoading(true)
    get<{ artifacts: Artifact[] }>('/api/artifacts')
      .then((data) => {
        const docs = (data.artifacts || []).filter(a =>
          !a.content_type?.startsWith('image/')
        )
        setArtifacts(docs)
      })
      .catch(() => toast.error('Failed to load documents'))
      .finally(() => setLoading(false))
  }

  async function handleDelete(id: string) {
    if (!window.confirm('Delete this document?')) return
    try {
      await del(`/api/artifacts/${id}`)
      setArtifacts((prev) => prev.filter((a) => a.id !== id))
      toast.success('Document deleted')
    } catch {
      toast.error('Failed to delete document')
    }
  }

  return (
    <div className="flex flex-col h-full bg-background overflow-hidden p-6 max-w-5xl mx-auto w-full">
      <div className="flex items-center justify-between mb-8 shrink-0">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Documents</h1>
          <p className="text-muted-foreground mt-2">Files and documents generated by your agent.</p>
        </div>
      </div>

      <ScrollArea className="flex-1 bg-card rounded-xl border border-border/50 shadow-sm relative pr-4 pb-4">
        <div className="p-4 space-y-4">
          {loading ? (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {[1, 2, 3].map((i) => (
                <Skeleton key={i} className="h-[72px] w-full rounded-lg" />
              ))}
            </div>
          ) : artifacts.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-20 text-center">
              <div className="h-12 w-12 rounded-full bg-primary/10 flex items-center justify-center mb-4">
                <span className="text-primary text-xl">📄</span>
              </div>
              <h3 className="text-lg font-medium text-foreground mb-1">No documents yet</h3>
              <p className="text-muted-foreground text-sm max-w-sm">
                Documents and files generated by your agent will appear here.
              </p>
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {artifacts.map((a) => (
                <div key={a.id} className="relative group/card flex">
                   <div className="flex-1 min-w-0">
                     <ArtifactCard artifact={a} className="sm:w-full w-full" />
                   </div>
                   <button
                     onClick={() => handleDelete(a.id)}
                     aria-label={`Delete ${a.filename}`}
                     className="absolute top-2 right-2 p-1.5 rounded-md text-muted-foreground/30 hover:text-destructive hover:bg-destructive/10 transition-all"
                   >
                     <Trash2 className="h-3.5 w-3.5" />
                   </button>
                </div>
              ))}
            </div>
          )}
        </div>
      </ScrollArea>
    </div>
  )
}
