import { useEffect, useState } from 'react'
import { get, del } from '@/lib/api'
import { Artifact, ArtifactCard } from '@/components/ArtifactCard'
import { ScrollArea } from '@/components/ui/scroll-area'
import { Trash2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { toast } from 'sonner'
import { Skeleton } from '@/components/ui/skeleton'

export default function ArtifactsPage() {
  const [artifacts, setArtifacts] = useState<Artifact[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    loadArtifacts()
  }, [])

  function loadArtifacts() {
    setLoading(true)
    get<{ artifacts: Artifact[] }>('/api/artifacts')
      .then((data) => {
        setArtifacts(data.artifacts || [])
      })
      .catch(() => toast.error('Failed to load artifacts'))
      .finally(() => setLoading(false))
  }

  async function handleDelete(id: string) {
    if (!window.confirm('Delete this artifact?')) return
    try {
      await del(`/api/artifacts/${id}`)
      setArtifacts((prev) => prev.filter((a) => a.id !== id))
      toast.success('Artifact deleted')
    } catch {
      toast.error('Failed to delete artifact')
    }
  }

  return (
    <div className="flex flex-col h-full bg-background overflow-hidden p-6 max-w-5xl mx-auto w-full">
      <div className="flex items-center justify-between mb-8 shrink-0">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Artifacts</h1>
          <p className="text-muted-foreground mt-2">Manage files generated by your AI agents.</p>
        </div>
      </div>

      <ScrollArea className="flex-1 bg-card rounded-xl border border-border/50 shadow-sm relative pr-4 pb-4">
        <div className="p-4 space-y-4">
          {loading ? (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {[1, 2, 3].map((i) => (
                <Skeleton key={i} className="h-[72px] w-full rounded-lg" />
              ))}
            </div>
          ) : artifacts.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-20 text-center">
              <div className="h-12 w-12 rounded-full bg-primary/10 flex items-center justify-center mb-4">
                <span className="text-primary text-xl">📄</span>
              </div>
              <h3 className="text-lg font-medium text-foreground mb-1">No artifacts yet</h3>
              <p className="text-muted-foreground text-sm max-w-sm">
                Files generated by your agents during conversations will appear here.
              </p>
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {artifacts.map((a) => (
                <div key={a.id} className="relative group/card flex">
                   <div className="flex-1 min-w-0">
                     <ArtifactCard artifact={a} className="sm:w-full w-full" />
                   </div>
                   <div className="absolute top-2 right-2 opacity-0 group-hover/card:opacity-100 transition-opacity">
                      <Button variant="destructive" size="icon" className="h-8 w-8 rounded-sm opacity-80 hover:opacity-100" onClick={() => handleDelete(a.id)} aria-label={`Delete ${a.filename}`}>
                        <Trash2 className="h-4 w-4" />
                      </Button>
                   </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </ScrollArea>
    </div>
  )
}
