#!/usr/bin/env bash
# ============================================================================
# 01-files.sh — EVERY file and directory operation. Nothing else.
#
#   No git branch operations (that's 02-git.sh).
#   No worktrees (that's 03-containers.sh).
#
# Run:  cd ~/Projects/test/odigos && bash scripts/01-files.sh
#
# Safe to re-run. Prints what it does. Deletes are guarded by existence checks.
# Verified against the actual tree on 2026-08-12.
# ============================================================================

set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

say() { printf '\n\033[1m== %s\033[0m\n' "$*"; }
rm_f() { [ -e "$1" ] && { rm -rf "$1"; printf '   deleted  %s\n' "$1"; } || printf '   (gone)   %s\n' "$1"; }

# ----------------------------------------------------------------------------
say "1. Junk — 434MB, zero value"
# ----------------------------------------------------------------------------
# _to_delete/ is a folder I created because the Cowork device bridge cannot
# unlink files. Everything in it is dead:
#   odigos.db-wal (360MB) + odigos.db-shm  -> orphaned WAL, main DB gone since
#                                             13 Apr; SQLite cannot replay a WAL
#                                             with no database. Unrecoverable.
#   odigos-snap.tgz (77MB)                 -> my analysis snapshot
#   gitlocks/*.lock                        -> git locks the bridge stranded
#   local-mods/{uv.lock,project.yml}       -> regenerated by `uv sync` / serena
#   .__writetest                           -> my probe file
rm_f _to_delete
rm_f .snap                 # empty dir left after the snapshot moved out
rm_f odigos.db             # 0 bytes; the real DB is data/odigos.db
rm_f .DS_Store

say "2. Orphaned test-DB fragments in data/"
# WAL/SHM sidecars whose .db files no longer exist. Same situation, harmless.
rm_f data/test_final.db-shm
rm_f data/test_final.db-wal
rm_f data/test_evolution.db-shm
rm_f data/test_evolution.db-wal

# ----------------------------------------------------------------------------
say "3. Stale GEMINI handoff docs — 11 files, all April, all landed"
# ----------------------------------------------------------------------------
for f in \
  GEMINI.md \
  GEMINI-BACKGROUND-TASKS-HANDOFF.md \
  GEMINI-POLISH-HANDOFF.md \
  GEMINI-SERVICES-HANDOFF.md \
  docs/GEMINI-HANDOFF.md \
  docs/GEMINI-BUBBLE-HANDOFF.md \
  docs/GEMINI-IMAGES-HANDOFF.md \
  docs/GEMINI-PHASE5-HANDOFF.md \
  docs/GEMINI-PWA-HANDOFF.md \
  docs/GEMINI-VOICE-HANDOFF.md \
  docs/GEMINI-WORKSPACE-HANDOFF.md
do
  [ -e "$f" ] && git rm -q --ignore-unmatch "$f" && printf '   deleted  %s\n' "$f" || printf '   (gone)   %s\n' "$f"
done

# ----------------------------------------------------------------------------
say "4. My own scaffolding — superseded, so it goes"
# ----------------------------------------------------------------------------
# THE-PLAN.md absorbed all of these. Keeping them means two sources of truth,
# which is the exact failure mode this whole exercise is about.
rm_f docs/superpowers/plans/2026-08-12-decommission-and-rebuild.md
rm_f docs/superpowers/plans/2026-08-12-tiers-revision.md
rm_f docs/containers/README.md
rm_f docs/containers/setup-containers.sh   # replaced by scripts/03-containers.sh
rm_f phase0-cleanup.sh                     # split into 01-files + 02-git

# ----------------------------------------------------------------------------
say "5. .gitignore"
# ----------------------------------------------------------------------------
add() { grep -qxF "$1" .gitignore 2>/dev/null || { echo "$1" >> .gitignore; printf '   +  %s\n' "$1"; }; }

grep -q '# --- closeout 2026-08-12 ---' .gitignore 2>/dev/null \
  || printf '\n# --- closeout 2026-08-12 ---\n' >> .gitignore

add '.DS_Store'
add '_to_delete/'
add '.snap/'
add 'data/*.db'
add 'data/*.db-wal'
add 'data/*.db-shm'
add 'data/artifacts/'
add 'data/uploads/'
add 'data/conversations/'
add 'data/chroma/'
add 'data/subagents/'
add 'data/subagent_workspace/'
add 'data/audio/'
add 'data/files/'
add 'data/vapid_keys.json'

# NOT ignored, deliberately:
#   data/brain/  (8K)  and  data/agent/  (36K)
#     -> durable persona knowledge. memory/brain_writer.py writes them and
#        brain_reader.py rebuilds the DB from them. They are CONTENT, not
#        runtime state. Decide for yourself whether to commit them; this
#        script will not silently hide them.
#   data/kanban/, data/notebooks/, data/prompts/, data/sources/, data/wiki/
#     -> user content from the old local instance. Your call: commit as
#        fixtures, or archive out of the repo. Left visible on purpose.

# ----------------------------------------------------------------------------
say "6. Final tree check"
# ----------------------------------------------------------------------------
printf '   repo size:    %s\n' "$(du -sh . 2>/dev/null | cut -f1)"
printf '   data/ size:   %s\n' "$(du -sh data 2>/dev/null | cut -f1)"
printf '   root .md:     %s\n' "$(ls *.md 2>/dev/null | tr '\n' ' ')"
printf '\n   Next: bash scripts/02-git.sh\n\n'
