import { useState, useEffect } from 'react'
import { get } from '@/lib/api'
import { toast } from 'sonner'
import { Button } from '@/components/ui/button'
import { 
  Download, 
  MessageSquare, 
  Book, 
  FileText, 
  Layout,
  ExternalLink,
  Loader2
} from 'lucide-react'

interface DataCounts {
  conversations: number
  notebooks: number
  artifacts: number
  boards: number
}

export default function DataTab({ active }: { active?: boolean }) {
  const [counts, setCounts] = useState<DataCounts | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    async function load() {
      setLoading(true)
      try {
        const [convs, notes, arts, boards] = await Promise.all([
          get<{ total: number }>('/api/conversations?limit=1'),
          get<{ notebooks: any[] }>('/api/notebooks'),
          get<{ artifacts: any[] }>('/api/artifacts'),
          get<{ boards: any[] }>('/api/kanban/boards')
        ])
        setCounts({
          conversations: convs.total,
          notebooks: notes.notebooks.length,
          artifacts: arts.artifacts.length,
          boards: boards.boards.length
        })
      } catch {
        toast.error('Failed to load data counts')
      } finally {
        setLoading(false)
      }
    }
    load()
  }, [active])

  if (loading) {
    return (
      <div className="flex items-center justify-center py-12">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    )
  }

  if (!counts) return null

  const sections = [
    {
      id: 'conversations',
      name: 'Conversations',
      count: counts.conversations,
      icon: MessageSquare,
      description: 'Your full chat history with the agent.',
      action: 'Export all as Markdown',
      link: '/api/conversations/export?format=markdown', // Note: backend might need a bulk export
      note: 'Individual exports available in chat history.'
    },
    {
      id: 'notebooks',
      name: 'Notebooks',
      count: counts.notebooks,
      icon: Book,
      description: 'Long-form entries and journals.',
      action: 'Download Backup',
      note: 'Notebooks are automatically synced to data/notebooks/'
    },
    {
      id: 'artifacts',
      name: 'Artifacts',
      count: counts.artifacts,
      icon: FileText,
      description: 'Documents and files generated by the agent.',
      action: 'View All Artifacts',
      link: '/artifacts'
    },
    {
      id: 'boards',
      name: 'Kanban Boards',
      count: counts.boards,
      icon: Layout,
      description: 'Task boards and project management data.',
      action: 'Export (Coming Soon)',
      disabled: true
    }
  ]

  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 py-4 sm:py-6 space-y-6">
      <div className="space-y-1">
        <h2 className="text-lg font-semibold tracking-tight">Data & Export</h2>
        <p className="text-sm text-muted-foreground leading-relaxed">
          Manage and export your personal data from Odigos.
        </p>
      </div>

      <div className="grid grid-cols-1 gap-4 pt-2">
        {sections.map((s) => (
          <div key={s.id} className="flex flex-col sm:flex-row items-start sm:items-center justify-between p-5 rounded-xl border border-border/40 bg-card/50 hover:bg-muted/30 transition-colors gap-4">
            <div className="flex items-center gap-4">
              <div className="h-10 w-10 rounded-lg bg-primary/10 flex items-center justify-center shrink-0">
                <s.icon className="h-5 w-5 text-primary" />
              </div>
              <div className="space-y-0.5">
                <div className="flex items-center gap-2">
                  <h3 className="font-bold text-sm leading-none">{s.name}</h3>
                  <span className="text-xs px-1.5 py-0.5 rounded-full bg-muted font-semibold text-muted-foreground">
                    {s.count}
                  </span>
                </div>
                <p className="text-xs text-muted-foreground leading-relaxed">
                  {s.description}
                </p>
                {s.note && <p className="text-[10px] text-muted-foreground italic">{s.note}</p>}
              </div>
            </div>

            <div className="w-full sm:w-auto">
              {s.link ? (
                <Button 
                  variant="outline" 
                  size="sm" 
                  className="w-full sm:w-auto h-9 gap-2"
                  onClick={() => s.link && window.open(s.link, '_blank')}
                  disabled={s.disabled}
                >
                  <Download className="h-3.5 w-3.5" />
                  {s.action}
                </Button>
              ) : (
                <Button 
                  variant="ghost" 
                  size="sm" 
                  className="w-full sm:w-auto h-9 gap-2 text-muted-foreground"
                  disabled={s.disabled || !s.action.includes('Backup')}
                >
                  {s.action.includes('Soon') ? s.action : (
                    <>
                      <ExternalLink className="h-3.5 w-3.5" />
                      {s.action}
                    </>
                  )}
                </Button>
              )}
            </div>
          </div>
        ))}
      </div>

      <div className="rounded-lg border border-yellow-500/20 bg-yellow-500/5 p-4 mt-8">
        <div className="flex gap-3">
          <Download className="h-5 w-5 text-yellow-600 shrink-0 mt-0.5" />
          <div className="space-y-1">
            <h4 className="text-sm font-bold text-yellow-700">Full Database Backup</h4>
            <p className="text-xs text-yellow-600/80 leading-relaxed">
              For a complete backup of everything, you can download the <code className="bg-yellow-500/10 px-1 rounded">odigos.db</code> file directly from your server's <code className="bg-yellow-500/10 px-1 rounded">data/</code> directory.
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}
